name: 02-workflow-events
on:
    push:
    pull_request:
    schedule:
      - cron: '0 0 * * 0'  # Runs at midnight every Sunday
    workflow_dispatch:
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger event
        run: echo "I have been triggered by an ${{github.event_name}} event"