name: contexts-example
on:
  push:
  workflow_dispatch:  
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Job: ${{ github.job }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Event Path: ${{ github.event_path }}"
          echo "Workspace: ${{ github.workspace }}" 
      - name: Display Runner Info
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Temp: ${{ runner.temp }}"
          echo "Runner Tool Cache: ${{ runner.tool_cache }}"
      - name: Retrieve variables
        run: |
          echo "Variable Value: ${{ vars.MY_VARIABLE }}"

