name: 03-workflow-runners
on: push
jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu Runner
        run: echo "This job is running on an ${runs-on} runner"
  windows-job:
    runs-on: windows-latest
    steps:
      - name: Windows Runner
        run: |
            echo "This job is running on an ${runs-on} runner"
            echo "Runner OS ${RUNNER_OS}"
